title:            Jordi Pont-Tuset's site
description:      Welcome to my site.
url:              https://ars-ashuha.ru
disqus_shortname: jponttuset

owner:
  name:           Jordi Pont-Tuset
  avatar:         jordi.png
  bio:            I'm from a small town near Girona, Catalunya. Currently in Zürich, Switzerland. Passionate about computer vision, technology, running, and mountains.
  email:          jponttuset@gmail.com
  twitter: jponttuset
  linkedin: jponttuset
  github: jponttuset

# google_analytics: UA-52736040-1
# google_verify: https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here

links:
  - title: Curriculum
    url: /cv/
  - title: Publications
    url: /publications/
  - title: Code
    url: /code/
  - title: Blog
    url: /blog/

timezone:    Europe/Zurich
future:      true
pygments:    true
highlighter: rouge
markdown:    kramdown
kramdown:
  extensions: ["strikethrough"]
  
# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
